verus_git_url = "https://github.com/verus-lang/verus.git"
verus_refspec = "main"

[[project]]
name = "apas-verus"
git_url = "https://github.com/briangmilnes/APAS-VERUS.git"
refspec = "main"
crate_roots = ["src/lib.rs"]
extra_verus_args = [
    "--crate-type=lib",
    "--multiple-errors", "20",
    "--expand-errors",
    "--num-threads", "8",
    "-V", "new-mut-ref",
]
